name: CI

on:
  push:
    branches:
      - main
      - feat/**
      - fix/**
      - chore/**
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Install and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npx vitest run --reporter=verbose

      # Optional: run the simple test runner as a smoke check
      - name: Run simple test suite
        run: npm test
